" Install vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
                \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline'
Plug 'scrooloose/nerdtree'
Plug 'hdima/python-syntax'
Plug 'Vimjas/vim-python-pep8-indent'
Plug 'Yggdroot/indentLine'
Plug 'bronson/vim-trailing-whitespace'
Plug 'Shougo/neocomplete.vim'
Plug 'fatih/vim-go', {'do': ':GoInstallBinaries'}
Plug 'djoshea/vim-autoread'
Plug 'mitsuhiko/vim-jinja'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'hail2u/vim-css3-syntax'
Plug 'ap/vim-css-color'
Plug 'othree/html5.vim'
Plug 'qpkorr/vim-bufkill'
Plug 'joshdick/onedark.vim'
Plug 'Chiel92/vim-autoformat'
call plug#end()

let g:indentLine_char = '│'
let g:go_fmt_command = 'goimports'
let g:airline#extensions#tabline#enabled = 1
if (has("autocmd") && !has("gui_running"))
    augroup colorset
        autocmd!
        let s:white = { "gui": "#ABB2BF", "cterm": "145", "cterm16" : "7" }
        autocmd ColorScheme * call onedark#set_highlight("Normal", { "fg": s:white }) " `bg` will not be styled since there is no `bg` setting
    augroup END
endif
colorscheme onedark

syntax on
filetype plugin indent on
let &t_8f="\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b="\<Esc>[48;2;%lu;%lu;%lum"
set bg=dark
set termguicolors
set splitbelow splitright
set ttyfast lazyredraw
set history=500
set autoread
set ruler
set ignorecase smartcase
set hlsearch incsearch
set noerrorbells novisualbell
set encoding=utf8
set nobackup nowb noswapfile
set expandtab smarttab shiftwidth=4 tabstop=4 softtabstop=4
set autoindent smartindent
set wrap
set number
set so=2
set clipboard=unnamed
set hidden

autocmd FileType python setlocal colorcolumn=80
highlight ColorColumn ctermbg=235
autocmd FileType html setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType yaml setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType htmljinja setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType htmldjango setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType gohtmltmpl setlocal sw=2 ts=2 sts=2
au BufWrite html,javascript :Autoformat

let mapleader = ";"
let g:mapleader = ";"

nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l
nnoremap <C-n> :NERDTreeToggle<cr>
nnoremap <silent> <leader>= :vertical resize +4<cr>
nnoremap <silent> <leader>- :vertical resize -4<cr>
